# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'docker_hub'
    repository: 'yodamad/apigee-kickstart-drupal'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      9.x
      latest